services:
  antimeta-dashboard:
    image: ghcr.io/nayetdet/datasette:latest
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
      resources:
        limits:
          memory: 512M
    ports:
      - "6767:6767"
    volumes:
      - type: bind
        source: ./data
        target: /app/data
    environment:
      TZ: ${TZ}
